name: Build
on: [push, pull_request]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MeteorVersion:
          - "1.5"
          - "1.6"
          - "1.7"
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "{context}/${{ matrix.MeteorVersion }}.dockerfile"
          push: false
          tags: "docker-meteor:${{ matrix.MeteorVersion }}"